In [4]:
import HSUtilCSV as csvHelper

%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [5]:
dataframe = csvHelper.load_file("out.csv")
dataframe

Unnamed: 0    label  product_ids    numbers  invoice_ids       nouns  \
0             0    email            0   8.492498            0  115.348964   
1             1    email            0   8.531532            0   92.254273   
2             2    email            0   4.801111            0   66.617019   
3             3    email            0   7.667789            0  154.160271   
4             4  invoice            0  22.405702            0   47.398884   
5             5    email            0   8.817861            0   45.029420   
6             6  invoice            0  13.154978            0   14.827238   
7             7  invoice            0   5.766189            0   33.077835   
8             8  invoice            0  16.208022            0   40.177937   
9             9  invoice            0  14.308303            0   27.191829   
10           10  invoice            0   8.912309            0   19.296730   
11           11  invoice            0  23.037457            0   44.981665   
12           12    email            0   2.263164            0   73.820691   
13           13    email            0   5.552289            0  117.020204   
14           14  invoice            0  14.382155            0   71.747025   
15           15    email            0   6.413902            0   48.987990   
16           16    email            0   1.556516            0   64.513180   
17           17  invoice            0  12.575602            0   23.878724   
18           18    email            0   2.164700            0  105.602478   
19           19  invoice            0  13.730298            0   39.250505   
20           20  invoice            0  10.038891            0   45.111800   
21           21  invoice            0  12.757379            0   37.461819   
22           22  invoice            0  28.686533            0   64.344799   
23           23    email            0   2.205876            0   53.413139   
24           24    email            0   5.894830            0   45.766961   
25           25  invoice            0   9.194179            0   62.813866   
26           26    email            0   7.746734            0   40.239337   
27           27    email            0   4.453389            0   51.753434   
28           28    email            0   5.774730            0  108.997939   
29           29    email            0   2.114337            0   90.766138   
..          ...      ...          ...        ...          ...         ...   
970         970  invoice            0   7.639684            0   32.098263   
971         971  invoice            0  17.852493            0   33.163371   
972         972    email            0   9.167394            0  122.666121   
973         973  invoice            0  15.448782            0   12.019475   
974         974  invoice            0  21.506323            0   22.146899   
975         975  invoice            0   7.226705            0   21.724413   
976         976    email            0   2.108986            0  104.404940   
977         977  invoice            0   8.853385            0   26.829310   
978         978  invoice            0   9.596996            0   42.094432   
979         979  invoice            0   8.610440            0   52.854653   
980         980    email            0   1.582869            0   87.252271   
981         981    email            0   4.326518            0   32.364988   
982         982    email            0   5.397659            0   86.844608   
983         983  invoice            0  11.921751            0   31.067195   
984         984  invoice            0   8.287508            0   19.272792   
985         985  invoice            0   6.103252            0   33.175090   
986         986  invoice            0  17.475935            0   40.873055   
987         987    email            0   1.908639            0  113.137117   
988         988    email            0   7.592629            0   59.627966   
989         989    email            0   9.305494            0   72.249563   
9

In [6]:
#splict the labels into booleans
dataframe['email']= (dataframe['label']=='email').astype(int)
dataframe['invoice']= (dataframe['label']=='invoice').astype(int)

#grab the label categories
labels = dataframe.ix[:,['email', 'invoice']]
labels

#remove the labels from the data
dataframe = dataframe.drop(['label','email','invoice','Unnamed: 0'], axis=1)
dataframe[0:10]

product_ids    numbers  invoice_ids       nouns      verbs  adjectives  \
0            0   8.492498            0  115.348964  25.647991   46.501078   
1            0   8.531532            0   92.254273  23.146700   19.381920   
2            0   4.801111            0   66.617019  31.507167   16.071230   
3            0   7.667789            0  154.160271  25.697308   47.468817   
4            0  22.405702            0   47.398884  10.106618   14.968691   
5            0   8.817861            0   45.029420  11.202883   13.487382   
6            0  13.154978            0   14.827238   4.588548    7.606447   
7            0   5.766189            0   33.077835   4.311295    9.527776   
8            0  16.208022            0   40.177937   8.870523   18.904601   
9            0  14.308303            0   27.191829   2.076847    9.092072   

   conjunctions  small_blocks  med_blocks  large_blocks  total_words  
0      1.202787      8.320143    8.825822      3.983797   191.941903  
1      0.000000      3.683311    6.949447      6.767945   119.653185  
2      0.000000      5.980526    6.452756      9.911710   108.097488  
3      1.217393      5.589100    6.411587      7.629462   236.012079  
4      0.000000     28.532538    7.152750      6.752953    95.834577  
5      0.000000      0.000000    3.420023      3.795903    90.202611  
6      0.000000     13.474829   12.579944      1.486279    60.990858  
7      0.000000     14.304745    7.177663      4.077856    55.707886  
8      0.000000     24.201877    5.938880      6.122907   117.009344  
9      0.000000     13.816756    7.267984      2.979067    74.197876

In [7]:
#convert the dataframs to matrixes
input_data = dataframe.as_matrix()
input_labels = labels.as_matrix()

In [8]:
input_data[0]

array([   0.        ,    8.49249848,    0.        ,  115.34896359,
         25.64799073,   46.50107777,    1.20278659,    8.32014335,
          8.82582243,    3.98379736,  191.94190291])

In [9]:
input_labels

array([[1, 0],
       [1, 0],
       [1, 0],
       ..., 
       [0, 1],
       [1, 0],
       [0, 1]])

In [10]:
#Tensorflow params
learning_rate = 0.00001
training_epochs= 100000
display_step = 50
n_samples = input_labels.size

In [11]:
#Tensorflow placeholder (the tensors to hold our data)
x = tf.placeholder(tf.float32, [None, 11])

#Weights
W = tf.Variable(tf.zeros([11,2]))

#biases
b = tf.Variable(tf.zeros([2]))

#activation function
y_values = tf.add(tf.matmul(x, W), b)
y= tf.nn.softmax(y_values)

#Tensorflow placeholder (the tensor to hold our labels)
y_ = tf.placeholder(tf.float32, [None,2])

In [12]:
#cost function is means squared error
cost = tf.reduce_sum(tf.pow(y_ - y, 2))/(2*n_samples)
#Gradient decent optimizer
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [13]:
#Initialization!
init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [14]:
#Lets train
for i in range(training_epochs):
    sess.run(optimizer, feed_dict={x: input_data, y_: input_labels})
    
    if(i) % display_step == 0:
        cc = sess.run(cost, feed_dict={x: input_data, y_:input_labels})
        print "Training step:", '%04d' % i , "cost=", "{:.9f}".format(cc)
        
print "Optimization done..."
training_cost = sess.run(cost, feed_dict={x: input_data, y_:input_labels})
print "Final cost = ", training_cost, "W=", sess.run(W), "b=", sess.run(b), '\n'

Training step: 0000 cost= 0.124772064
Training step: 0050 cost= 0.118277378
Training step: 0100 cost= 0.114890300
Training step: 0150 cost= 0.111943252
Training step: 0200 cost= 0.109134659
Training step: 0250 cost= 0.106430389
Training step: 0300 cost= 0.103825040
Training step: 0350 cost= 0.101316407
Training step: 0400 cost= 0.098901950
Training step: 0450 cost= 0.096579067
Training step: 0500 cost= 0.094344757
Training step: 0550 cost= 0.092196032
Training step: 0600 cost= 0.090129681
Training step: 0650 cost= 0.088142455
Training step: 0700 cost= 0.086231247
Training step: 0750 cost= 0.084392853
Training step: 0800 cost= 0.082624115
Training step: 0850 cost= 0.080922045
Training step: 0900 cost= 0.079283580
Training step: 0950 cost= 0.077706032
Training step: 1000 cost= 0.076186523
Training step: 1050 cost= 0.074722409
Training step: 1100 cost= 0.073311143
Training step: 1150 cost= 0.071950339
Training step: 1200 cost= 0.070637695
Training step: 1250 cost= 0.069371030
Training ste

Training step: 10950 cost= 0.017054612
Training step: 11000 cost= 0.016995663
Training step: 11050 cost= 0.016937176
Training step: 11100 cost= 0.016879128
Training step: 11150 cost= 0.016821522
Training step: 11200 cost= 0.016764343
Training step: 11250 cost= 0.016707599
Training step: 11300 cost= 0.016651280
Training step: 11350 cost= 0.016595382
Training step: 11400 cost= 0.016539901
Training step: 11450 cost= 0.016484821
Training step: 11500 cost= 0.016430156
Training step: 11550 cost= 0.016375881
Training step: 11600 cost= 0.016322009
Training step: 11650 cost= 0.016268522
Training step: 11700 cost= 0.016215431
Training step: 11750 cost= 0.016162723
Training step: 11800 cost= 0.016110398
Training step: 11850 cost= 0.016058438
Training step: 11900 cost= 0.016006844
Training step: 11950 cost= 0.015955612
Training step: 12000 cost= 0.015904756
Training step: 12050 cost= 0.015854260
Training step: 12100 cost= 0.015804112
Training step: 12150 cost= 0.015754307
Training step: 12200 cost

Training step: 21600 cost= 0.010058170
Training step: 21650 cost= 0.010039759
Training step: 21700 cost= 0.010021393
Training step: 21750 cost= 0.010003077
Training step: 21800 cost= 0.009984867
Training step: 21850 cost= 0.009966726
Training step: 21900 cost= 0.009948625
Training step: 21950 cost= 0.009930620
Training step: 22000 cost= 0.009912707
Training step: 22050 cost= 0.009894835
Training step: 22100 cost= 0.009877017
Training step: 22150 cost= 0.009859322
Training step: 22200 cost= 0.009841669
Training step: 22250 cost= 0.009824049
Training step: 22300 cost= 0.009806555
Training step: 22350 cost= 0.009789118
Training step: 22400 cost= 0.009771717
Training step: 22450 cost= 0.009754394
Training step: 22500 cost= 0.009737173
Training step: 22550 cost= 0.009719988
Training step: 22600 cost= 0.009702840
Training step: 22650 cost= 0.009685818
Training step: 22700 cost= 0.009668848
Training step: 22750 cost= 0.009651907
Training step: 22800 cost= 0.009635054
Training step: 22850 cost

Training step: 32350 cost= 0.007273296
Training step: 32400 cost= 0.007264176
Training step: 32450 cost= 0.007255119
Training step: 32500 cost= 0.007246078
Training step: 32550 cost= 0.007237056
Training step: 32600 cost= 0.007228040
Training step: 32650 cost= 0.007219045
Training step: 32700 cost= 0.007210060
Training step: 32750 cost= 0.007201121
Training step: 32800 cost= 0.007192235
Training step: 32850 cost= 0.007183363
Training step: 32900 cost= 0.007174508
Training step: 32950 cost= 0.007165666
Training step: 33000 cost= 0.007156834
Training step: 33050 cost= 0.007148012
Training step: 33100 cost= 0.007139251
Training step: 33150 cost= 0.007130523
Training step: 33200 cost= 0.007121820
Training step: 33250 cost= 0.007113125
Training step: 33300 cost= 0.007104442
Training step: 33350 cost= 0.007095773
Training step: 33400 cost= 0.007087119
Training step: 33450 cost= 0.007078520
Training step: 33500 cost= 0.007069956
Training step: 33550 cost= 0.007061400
Training step: 33600 cost

Training step: 43000 cost= 0.005764953
Training step: 43050 cost= 0.005759422
Training step: 43100 cost= 0.005753909
Training step: 43150 cost= 0.005748446
Training step: 43200 cost= 0.005742991
Training step: 43250 cost= 0.005737547
Training step: 43300 cost= 0.005732107
Training step: 43350 cost= 0.005726680
Training step: 43400 cost= 0.005721258
Training step: 43450 cost= 0.005715841
Training step: 43500 cost= 0.005710429
Training step: 43550 cost= 0.005705020
Training step: 43600 cost= 0.005699622
Training step: 43650 cost= 0.005694229
Training step: 43700 cost= 0.005688882
Training step: 43750 cost= 0.005683552
Training step: 43800 cost= 0.005678223
Training step: 43850 cost= 0.005672903
Training step: 43900 cost= 0.005667589
Training step: 43950 cost= 0.005662284
Training step: 44000 cost= 0.005656988
Training step: 44050 cost= 0.005651700
Training step: 44100 cost= 0.005646419
Training step: 44150 cost= 0.005641143
Training step: 44200 cost= 0.005635873
Training step: 44250 cost

Training step: 53700 cost= 0.004798258
Training step: 53750 cost= 0.004794550
Training step: 53800 cost= 0.004790842
Training step: 53850 cost= 0.004787142
Training step: 53900 cost= 0.004783441
Training step: 53950 cost= 0.004779744
Training step: 54000 cost= 0.004776052
Training step: 54050 cost= 0.004772394
Training step: 54100 cost= 0.004768752
Training step: 54150 cost= 0.004765112
Training step: 54200 cost= 0.004761472
Training step: 54250 cost= 0.004757838
Training step: 54300 cost= 0.004754208
Training step: 54350 cost= 0.004750580
Training step: 54400 cost= 0.004746952
Training step: 54450 cost= 0.004743330
Training step: 54500 cost= 0.004739712
Training step: 54550 cost= 0.004736095
Training step: 54600 cost= 0.004732491
Training step: 54650 cost= 0.004728891
Training step: 54700 cost= 0.004725289
Training step: 54750 cost= 0.004721692
Training step: 54800 cost= 0.004718103
Training step: 54850 cost= 0.004714513
Training step: 54900 cost= 0.004710957
Training step: 54950 cost

Training step: 64250 cost= 0.004132486
Training step: 64300 cost= 0.004129801
Training step: 64350 cost= 0.004127122
Training step: 64400 cost= 0.004124443
Training step: 64450 cost= 0.004121767
Training step: 64500 cost= 0.004119094
Training step: 64550 cost= 0.004116421
Training step: 64600 cost= 0.004113751
Training step: 64650 cost= 0.004111082
Training step: 64700 cost= 0.004108415
Training step: 64750 cost= 0.004105750
Training step: 64800 cost= 0.004103090
Training step: 64850 cost= 0.004100434
Training step: 64900 cost= 0.004097780
Training step: 64950 cost= 0.004095126
Training step: 65000 cost= 0.004092510
Training step: 65050 cost= 0.004089894
Training step: 65100 cost= 0.004087282
Training step: 65150 cost= 0.004084672
Training step: 65200 cost= 0.004082064
Training step: 65250 cost= 0.004079457
Training step: 65300 cost= 0.004076855
Training step: 65350 cost= 0.004074254
Training step: 65400 cost= 0.004071654
Training step: 65450 cost= 0.004069056
Training step: 65500 cost

Training step: 74950 cost= 0.003632021
Training step: 75000 cost= 0.003629987
Training step: 75050 cost= 0.003627954
Training step: 75100 cost= 0.003625920
Training step: 75150 cost= 0.003623892
Training step: 75200 cost= 0.003621868
Training step: 75250 cost= 0.003619844
Training step: 75300 cost= 0.003617821
Training step: 75350 cost= 0.003615798
Training step: 75400 cost= 0.003613777
Training step: 75450 cost= 0.003611756
Training step: 75500 cost= 0.003609740
Training step: 75550 cost= 0.003607723
Training step: 75600 cost= 0.003605707
Training step: 75650 cost= 0.003603690
Training step: 75700 cost= 0.003601678
Training step: 75750 cost= 0.003599663
Training step: 75800 cost= 0.003597654
Training step: 75850 cost= 0.003595656
Training step: 75900 cost= 0.003593678
Training step: 75950 cost= 0.003591701
Training step: 76000 cost= 0.003589725
Training step: 76050 cost= 0.003587750
Training step: 76100 cost= 0.003585779
Training step: 76150 cost= 0.003583809
Training step: 76200 cost

Training step: 85550 cost= 0.003249069
Training step: 85600 cost= 0.003247465
Training step: 85650 cost= 0.003245859
Training step: 85700 cost= 0.003244254
Training step: 85750 cost= 0.003242651
Training step: 85800 cost= 0.003241047
Training step: 85850 cost= 0.003239445
Training step: 85900 cost= 0.003237845
Training step: 85950 cost= 0.003236245
Training step: 86000 cost= 0.003234646
Training step: 86050 cost= 0.003233048
Training step: 86100 cost= 0.003231452
Training step: 86150 cost= 0.003229856
Training step: 86200 cost= 0.003228264
Training step: 86250 cost= 0.003226674
Training step: 86300 cost= 0.003225085
Training step: 86350 cost= 0.003223497
Training step: 86400 cost= 0.003221914
Training step: 86450 cost= 0.003220331
Training step: 86500 cost= 0.003218772
Training step: 86550 cost= 0.003217217
Training step: 86600 cost= 0.003215663
Training step: 86650 cost= 0.003214110
Training step: 86700 cost= 0.003212557
Training step: 86750 cost= 0.003211008
Training step: 86800 cost

Training step: 96300 cost= 0.002939525
Training step: 96350 cost= 0.002938232
Training step: 96400 cost= 0.002936941
Training step: 96450 cost= 0.002935651
Training step: 96500 cost= 0.002934361
Training step: 96550 cost= 0.002933073
Training step: 96600 cost= 0.002931784
Training step: 96650 cost= 0.002930496
Training step: 96700 cost= 0.002929208
Training step: 96750 cost= 0.002927924
Training step: 96800 cost= 0.002926637
Training step: 96850 cost= 0.002925352
Training step: 96900 cost= 0.002924067
Training step: 96950 cost= 0.002922782
Training step: 97000 cost= 0.002921499
Training step: 97050 cost= 0.002920215
Training step: 97100 cost= 0.002918932
Training step: 97150 cost= 0.002917650
Training step: 97200 cost= 0.002916370
Training step: 97250 cost= 0.002915090
Training step: 97300 cost= 0.002913810
Training step: 97350 cost= 0.002912530
Training step: 97400 cost= 0.002911251
Training step: 97450 cost= 0.002909973
Training step: 97500 cost= 0.002908696
Training step: 97550 cost

In [15]:
something = sess.run(y, feed_dict={x: input_data})


In [16]:
something[18]

array([ 0.99490827,  0.00509174], dtype=float32)

In [17]:
labels[-10:]


email  invoice
990      1        0
991      0        1
992      1        0
993      1        0
994      1        0
995      0        1
996      1        0
997      0        1
998      1        0
999      0        1

In [18]:
single_predict = sess.run(y, feed_dict={x: input_data[999:1000]})
single_predict

array([[ 0.05259405,  0.94740593]], dtype=float32)

In [19]:
saver = tf.train.Saver()
save_path = saver.save(sess, './models/classifier.ckpt')

In [20]:
save_path

'./models/classifier.ckpt'